name: galaxy-community-activities
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - pandas <3.0
  - c-compiler
  - compilers
  - cxx-compiler
  - ruby
  - pip
  - networkx
  - scikit-image
  - numpy
  - scipy
  - matplotlib # required as plugin for skimage.io.imread
  - pygraphviz
  - pip:
    - PyGithub
    - pyyaml
    - tqdm
    - python-liquid
