name: Build and deploy

on:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: [Update cache]
    types: [completed]

jobs:

  build_and_deploy:
    name: Build and deploy report
    permissions:
      contents: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:

      - name: Initialize
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          fetch-depth: 1  # With this git commit --amend will overwrite the whole history

      - name: Fetch sources
        shell: bash
        run: |
          git clone https://github.com/kostrykin/galaxy-community-activities.git
          rm -rf galaxy-community-activities/.git
          rm -rf report
          [ ! -d cache ] || rm -rf cache
          mv -f galaxy-community-activities/* ./

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: galaxy-community-activities
          environment-file: environment.yml

      - name: Install Jekyll
        run: |
          conda info
          gem install jekyll
          ln -s $(which ruby) $CONDA_PREFIX/share/rubygems/bin/

      - name: Build report
        run: |
            python -m activities.cli --report
            mv report/_site ./
            rm -rf report
            mv _site report

      - name: Squash and deploy to GitHub Pages
        uses: stefanzweifel/git-auto-commit-action@v7
        if: github.event_name != 'pull_request'
        with:
          file_pattern: 'report'
          commit_message: Build and deploy report
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
