name: Build and deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'  ## At 01:00 AM on every Monday

jobs:
  update_cache:
    name: Update cache
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install pandas PyGithub pyyaml tqdm

      - name: Update cache
        run: python -m activities.cli --fetch
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit and push updated cache
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update cache

  build_report:
    needs: update_cache
    name: Build and deploy report
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Fetch sources
        shell: bash
        run: |
          git clone https://github.com/kostrykin/galaxy-community-activities.git
          rm -rf galaxy-community-activities/.git
          rm -rf report
          [ ! -d cache ] || mv cache cache.old
          mv -f galaxy-community-activities/* ./
          [ ! -d cache.old/avatars ] || mv cache.old/avatars cache/avatars
          [ ! -d cache.old ] || rm -rf cache.old

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: galaxy-community-activities
          environment-file: environment.yml

      - name: Install Jekyll
        shell: bash
        run: |
          conda info
          gem install jekyll
          ln -s $(which ruby) $CONDA/share/rubygems/bin/

      - name: Build report
        run: python -m activities.cli --report

      - name: Deploy to GitHub Pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'report/* cache/avatars'
          commit_message: Build and deploy report
