name: Update cache

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'  ## At 01:00 AM on every Monday

jobs:
  update_cache:
    name: Update cache
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install pandas PyGithub pyyaml tqdm

      - name: Update cache
        run: python -m activities.cli --fetch
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit and push updated cache
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update cache
